name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    - name: Build Docker images using Compose
      run: docker compose build
        
    - name: Tag and Push Docker image
      run: |
        docker tag trend_shield-backend ${{ secrets.ECR_REPOSITORY_BACKEND }}:latest
        docker push ${{ secrets.ECR_REPOSITORY_BACKEND }}:latest

        docker tag trend_shield-worker ${{ secrets.ECR_REPOSITORY_CELERY }}:latest
        docker push ${{ secrets.ECR_REPOSITORY_CELERY }}:latest

        docker tag trend_shield-frontend ${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest
        docker push ${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest


    - name: Deploy to EC2 backend servers
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.BACKEND_SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

          docker stop worker || true
          docker rm worker || true
          echo "ðŸ”¥ Deep cleaning Docker..."
          docker system prune -a --volumes -f
          rm -rf /var/lib/docker/tmp/*
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get clean
          sudo journalctl --vacuum-time=1d
          
          docker pull ${{ secrets.ECR_REPOSITORY_BACKEND }}:latest
          docker run -d   --name trendshield_backend   -p 80:80   -p 443:80  ${{ secrets.ECR_REPOSITORY_BACKEND }}:latest
          exit

    - name: Deploy to celery EC2 server
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.CELERY_SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

          docker stop worker || true
          docker rm worker || true
          echo "ðŸ”¥ Deep cleaning Docker..."
          docker system prune -a --volumes -f
          rm -rf /var/lib/docker/tmp/*
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get clean
          sudo journalctl --vacuum-time=1d

          docker pull ${{ secrets.ECR_REPOSITORY_CELERY }}:latest
          docker run -d --name worker -p 80:80 ${{ secrets.ECR_REPOSITORY_CELERY }}:latest
          exit
    

    - name: Deploy to frontend EC2 server
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.FRONTEND_SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

          docker stop worker || true
          docker rm worker || true
          echo "ðŸ”¥ Deep cleaning Docker..."
          docker system prune -a --volumes -f
          rm -rf /var/lib/docker/tmp/*
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get clean
          sudo journalctl --vacuum-time=1d
          docker pull ${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest
          docker run --name frontend -d -p 81:3000 ${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest
          exit
    
